### ISSUE TITLE
O que posso ajudar?

### ISSUE THREAD

**Issue by felquis** [IonicBrazil/ionic-weekly#1]
Por um tempo em 2012 ajudei na elaboração da BrazilJS Weekly, e aprendi sobre o funcionamento do MailChimp.

Hoje foi adotado um modelo descentralizado, em que é criada uma issue modelo e todos os comentários são revisados e incluído na próxima Weekly.

Sugestão: Usar o mesmo modelo da BrazilJS com as issues próxima issue https://github.com/braziljs/weekly/issues/66

Não sei quem teve a iniciativa do projeto, também não sei se já existe outras iniciativas do tipo, então só vou deixar minha sugestão para continuar. Por que é sim algo interessante.

**Comment by juarezpaf** [comment]
Tem uma conta no Twitter https://twitter.com/ionicweekly mas bem desatualizada.

**Comment by raphaelpor** [comment]
Já temos inclusive, um repositório para isso. Só não tive tempo de elaborar. :(
https://github.com/IonicBrazil/ionic-weekly

Se alguém puder ajudar... :dancers:

**Comment by raphaelpor** [comment]
Criei um site simples para iniciarmos que já está integrado com a lista do Mailchimp da Ionic Brazil.

Está temporariamente, num repositório do meu profile. Mas se aprovarem, podemos migrar para a Ionic Brazil. :wink: 
Link: https://github.com/raphaelpor/ionic-weekly

**Comment by raphaelpor** [comment]
http://ionicbrazil.github.io/ionic-weekly/
:rocket:

**Comment by juarezpaf** [comment]
@raphaelpor show demais! Vamos tentar fazer uma atualização colocando o logo do Ionic em cima e o do IonicBrazil discretamente no footer. ;)

**Comment by raphaelpor** [comment]
Vou ver se consigo fazer isso, ainda hoje. :smiley:

**Comment by raphaelpor** [comment]
Ionic logo: done! :rocket:
