### ISSUE TITLE
Necessário criar um README.md

### ISSUE THREAD

**Issue by raphaelpor** [IonicBrazil/ionic-weekly#2]
Precisamos criar um, contendo no mínimo a descrição do repositório e as instruções de colaboração.
:rocket:

**Comment by juarezpaf** [comment]
Yeap! Talvez eu consiga criar hoje a noite. o/

**Comment by raphaelpor** [comment]
Aeew! :+1:

**Comment by raphaelpor** [comment]
Criei um bem básico. Se puder melhorar... :wink:
